language: java
sudo : true
services:
  - postgresql
env:
  global:
  - PGPORT=5432
test:
    adapter: postgresql
    database: GatewayDB
    username: postgres
    encoding: utf8
script: 
    - psql -c 'create database GatewayDB;' -U postgres
    - mvn install -DskipTests=true 
