language: java
sudo : true
services:
  - postgresql
env:
  global:
  - PGPORT=5433
before_script:
  - sudo rm /usr/local/var/postgres/postmaster.pid
  - psql -c 'create database GatewayDB;' -U postgres
test:
    adapter: postgresql
    database: GatewayDB
    username: postgres
    encoding: utf8
script: 
    - mvn clean install
