language: java
sudo : true
services:
  - postgresql
env:
  global:
  - PGPORT=5432
before_script:
  - psql -c 'create database gatewaydb;' -U postgres
  - psql -h localhost --username=postgres --list
test:
    adapter: postgresql
    database: gatewaydb
    username: postgres
    encoding: utf8
script: 
    - mvn clean install
